name: Proposez une ressource 
description: Venez proposez votre propre ressource 
title: "[Ma ressource]: "
labels: ["proposition de ressource"]
assignees:
  - WolfyzDev

body:
  - type: markdown
    attributes:
      value: |
        Merci pour votre participation
  - type: textarea
    id: Nom de la ressource
    attributes:
      label: Propostion de ressource 
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
   - type: dropdown
    id: version
    attributes:
      label: Souhaitez-vous être noté comme contributeur ? 
      description: 
      options:
        - Oui (Default)
        - Non (Edge)
    validations:
      required: true
