name: Proposez une ressource 
description: Venez proposez votre propre ressource 
title: "[Bug]: "
labels: ["proposition de ressource"]
assignees:
  - WolfyzDev

body:
  - type: markdown
    attributes:
      value: |
        Merci pour votre participation
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Quel nom ? 
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
   - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
