name: Milestone 
description: Liste des tâches à faire ce mois-ci (réservé aux admins)
title: "[Milestone]: "
labels: ["Milestone"]
assignees:
  - WolfyzDev
  - Sn0wAlice
  - ena0
  - LACOSTAR91
  - julescrepi
body:
  
  - type: textarea
    id: MinorTask
    attributes:
      label: Modifications mineurs (y compris sur le Discord) 
    validations:
      required: false
  - type: textarea
    id: complementaryTask
    attributes:
      label: Autres tâches 
    validations:
      required: false
